api_users:
    path: /api/users
    methods: [GET, POST]
    controller: App\Controller\UserController::index

api_users_show:
    path: /api/users/{id}
    methods: [GET]
    controller: App\Controller\UserController::show

api_users_create:
    path: /api/users
    methods: [POST]
    controller: App\Controller\UserController::create

